name: "Analyze"

on:
  push:
  pull_request:
#github environment variables
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: tonasodji/test_pull_request
          ref: main
          
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          #echo "$GITHUB_CONTEXT"
          echo "//test" >> main.c

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOK }}
          branch: main
          add-paths: |
            *.c
          title: test pr
          
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1
      
      - name: Analyze
        run: |
          git clone https://github.com/tonasodji/pvs.git
          cd pvs
          pvs-studio-analyzer trace -- make -j8
          pvs-studio-analyzer analyze -j8 -l PVS-Studio.lic -o PVS-Studio.log
          plog-converter PVS-Studio.log -t sarif -o results.sarif


      - name: reports SARIF
        run: |
          (gzip -c pvs/results.sarif | base64 -w0) > results
          gh api --method POST -H "Accept: application/vnd.github+json" \
          /repos/$GITHUB_REPOSITORY/code-scanning/sarifs \
          -f commit_sha="f4f6f3d0a77638eb68675bf9e8c731380a3bdede" -f ref="refs/pull/27/merge" -F sarif=@results
